### ISSUE TITLE
EraseBlock() no longer works for 25Q16

### ISSUE THREAD

**Issue by dshadoff** [adafruit/Adafruit_QSPI#7]
With the 3.0 release standardizing functions across multiple devices, it looks like I encountered some fallout.

EraseBlock() continues to be a function which compiles, although it no longer erases a block on the ItsyBitsy M4’s 25Q16 QSPI memory.

This wouldn’t be so bad, except a loop of eraseSector() calls is about 10 times slower.

I would like to request that the functionality be brought back, as it was quite useful.

**Comment by ladyada** [comment]
@hathach will check this out after they're back from break :)

**Comment by dshadoff** [comment]
I tried the version from @hathach 's master, and it works fine for me - and much faster than eraseSector(), as expected.

...At least it worked for me on the ItsyBitsy M4 and its GD25Q16 (not sure about other platform permutations).

**Comment by ladyada** [comment]
gr8!
