### ISSUE TITLE
Adafruit_QSPI_Flash.cpp, lines 154 thru 158 have undefined variables

### ISSUE THREAD

**Issue by ChuckVanzant** [adafruit/Adafruit_QSPI#9]
In file Adafruit_QSPI_Flash.cpp, lines 154 thru 158 have the following undefined variables specified which causes a build error. Commenting out these lines allows the sample script PyPortal_ArduinoSelfTest.ino to build and execute.

  // Adafruit_SPIFlash variables
  currentAddr = 0;
  addrsize = 24;
  totalsize = _flash_dev->total_size;
  pagesize = QSPI_FLASH_PAGE_SIZE;
  pages = totalsize/QSPI_FLASH_PAGE_SIZE;

**Comment by hathach** [comment]
this library is deprecated, please use https://github.com/adafruit/Adafruit_SPIFlash instead
